import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './components/common/Header';
import Footer from './components/common/Footer'; // <-- 1. Footer import karo

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      {/* 2. min-h-screen lagao taaki body poori screen ki height le */}
      <body className="min-h-screen flex flex-col">

        <Header />

        {/* 3. flex-grow lagane se yeh saari khaali space cover kar lega aur footer neeche chala jayega */}
        <main className="flex-grow">
          {children}
        </main>
        
        <Footer /> {/* 4. Footer sabse end mein */}

       </body>
    </html>
  );
}